export const login_background_Image = "https://shorturl.at/3hGkK";

const bannerImg = {
  moto: "https://rukminim2.flixcart.com/fk-p-flap/1600/270/image/83c20c04eae96670.jpg?q=20",
  discount: "http://tiny.cc/dis-count",
  bannerBazzar: "http://tiny.cc/banner-bazzar",
};

export const category = [
  {
    id: 1,
    brandName: "Apple",
    title: "Apple",
    thumbnail: "http://tiny.cc/zb3hzz",

  },
  {
    id: 2,
    brandName: "Motorola",
    title: "Motorola",

    thumbnail: "http://tiny.cc/1c3hzz",
  },
  {
    id: 3,
    brandName: "Samsung",
    title: "Samsung",

    thumbnail: "http://tiny.cc/sam-sung",
  },
  {
    id: 4,
    brandName: "Google",
    title: "Pixel",

    thumbnail: "https://rb.gy/zqv00f",
  },
  {
    id: 5,
    brandName: "OnePlus",
    title: "OnePlus",

    thumbnail: "http://tiny.cc/one_plus",
  },
  {
    id: 6,
    brandName: "Nothing",
    title: "Nothing",

    thumbnail: "https://rb.gy/i628yi",
  },
  {
    id: 7,
    brandName: "browse-mobiles",
    title: "View All",

    thumbnail: "https://res.cloudinary.com/dooxbo8sg/image/upload/v1737626047/ModernMobiles/Others/mobile_collection.png",
  }
];

// https://github.com/pbakondy/ios-device-list/blob/master/iphone.json
export const iphone = [
  // {
  //   Generation: "iPhone 11 Pro Max",
  //   ANumber: ["A2161"],
  //   Bootrom: ["Bootrom 4479.0.0.100.4"],
  //   FCCID: ["BCG-E3309A"],
  //   InternalName: "D431AP",
  //   Identifier: "iPhone12,5",
  //   Models: [
  //     {
  //       Color: "Gold",
  //       Storage: "64 GB",
  //       Model: ["MWFC2", "MWG42", "MWFQ2", "MWGH2", "MWH12"],
  //     },
  //     {
  //       Color: "Gold",
  //       Storage: "256 GB",
  //       Model: ["MWFG2", "MWG82", "MWFV2", "MWGM2", "MWH62"],
  //     },
  //     {
  //       Color: "Gold",
  //       Storage: "512 GB",
  //       Model: ["MWFL2", "MWGD2", "MWG02", "MWGR2", "MWHA2"],
  //     },
  //     {
  //       Color: "Midnight Green",
  //       Storage: "64 GB",
  //       Model: ["MWFD2", "MWG52", "MWFR2", "MWGJ2", "MWH22"],
  //     },
  //     {
  //       Color: "Midnight Green",
  //       Storage: "256 GB",
  //       Model: ["MWFH2", "MWG92", "MWFW2", "MWGN2", "MWH72"],
  //     },
  //     {
  //       Color: "Midnight Green",
  //       Storage: "512 GB",
  //       Model: ["MWFM2", "MWGE2", "MWG12", "MWGT2", "MWHC2"],
  //     },
  //     {
  //       Color: "Silver",
  //       Storage: "64 GB",
  //       Model: ["MWFA2", "MWG32", "MWFP2", "MWGG2", "MWH02"],
  //     },
  //     {
  //       Color: "Silver",
  //       Storage: "256 GB",
  //       Model: ["MWFF2", "MWG72", "MWFU2", "MWGL2", "MWH52"],
  //     },
  //     {
  //       Color: "Silver",
  //       Storage: "512 GB",
  //       Model: ["MWFK2", "MWGC2", "MWFY2", "MWGQ2", "MWH92"],
  //     },
  //     {
  //       Color: "Space Gray",
  //       Storage: "64 GB",
  //       Model: ["MWF92", "MWG22", "MWFN2", "MWGF2", "MWGY2"],
  //     },
  //     {
  //       Color: "Space Gray",
  //       Storage: "256 GB",
  //       Model: ["MWFE2", "MWG62", "MWFT2", "MWGK2", "MWH42"],
  //     },
  //     {
  //       Color: "Space Gray",
  //       Storage: "512 GB",
  //       Model: ["MWFJ2", "MWGA2", "MWFX2", "MWGP2", "MWH82"],
  //     },
  //   ],
  // },
  // {
  //   Generation: "iPhone 11 Pro Max",
  //   ANumber: ["A2220"],
  //   Bootrom: ["Bootrom 4479.0.0.100.4"],
  //   FCCID: ["BCG-E3309A"],
  //   InternalName: "D431AP",
  //   Identifier: "iPhone12,5",
  //   Models: [
  //     {
  //       Color: "Gold",
  //       Storage: "64 GB",
  //       Model: ["MWHG2"],
  //     },
  //     {
  //       Color: "Gold",
  //       Storage: "256 GB",
  //       Model: ["MWHL2"],
  //     },
  //     {
  //       Color: "Gold",
  //       Storage: "512 GB",
  //       Model: ["MWHQ2"],
  //     },
  //     {
  //       Color: "Midnight Green",
  //       Storage: "64 GB",
  //       Model: ["MWHH2"],
  //     },
  //     {
  //       Color: "Midnight Green",
  //       Storage: "256 GB",
  //       Model: ["MWHM2"],
  //     },
  //     {
  //       Color: "Midnight Green",
  //       Storage: "512 GB",
  //       Model: ["MWHR2"],
  //     },
  //     {
  //       Color: "Silver",
  //       Storage: "64 GB",
  //       Model: ["MWHF2"],
  //     },
  //     {
  //       Color: "Silver",
  //       Storage: "256 GB",
  //       Model: ["MWHK2"],
  //     },
  //     {
  //       Color: "Silver",
  //       Storage: "512 GB",
  //       Model: ["MWHP2"],
  //     },
  //     {
  //       Color: "Space Gray",
  //       Storage: "64 GB",
  //       Model: ["MWHD2"],
  //     },
  //     {
  //       Color: "Space Gray",
  //       Storage: "256 GB",
  //       Model: ["MWHJ2"],
  //     },
  //     {
  //       Color: "Space Gray",
  //       Storage: "512 GB",
  //       Model: ["MWHN2"],
  //     },
  //   ],
  // },
  // {
  //   Generation: "iPhone 11 Pro Max",
  //   ANumber: ["A2218"],
  //   Bootrom: ["Bootrom 4479.0.0.100.4"],
  //   FCCID: ["BCG-E3309A"],
  //   InternalName: "D431AP",
  //   Identifier: "iPhone12,5",
  //   Models: [
  //     {
  //       Color: "Gold",
  //       Storage: "64 GB",
  //       Model: ["MWEX2"],
  //     },
  //     {
  //       Color: "Gold",
  //       Storage: "256 GB",
  //       Model: ["MWF32"],
  //     },
  //     {
  //       Color: "Gold",
  //       Storage: "512 GB",
  //       Model: ["MWF72"],
  //     },
  //     {
  //       Color: "Midnight Green",
  //       Storage: "64 GB",
  //       Model: ["MWF02"],
  //     },
  //     {
  //       Color: "Midnight Green",
  //       Storage: "256 GB",
  //       Model: ["MWF42"],
  //     },
  //     {
  //       Color: "Midnight Green",
  //       Storage: "512 GB",
  //       Model: ["MWF82"],
  //     },
  //     {
  //       Color: "Silver",
  //       Storage: "64 GB",
  //       Model: ["MWEW2"],
  //     },
  //     {
  //       Color: "Silver",
  //       Storage: "256 GB",
  //       Model: ["MWF22"],
  //     },
  //     {
  //       Color: "Silver",
  //       Storage: "512 GB",
  //       Model: ["MWF62"],
  //     },
  //     {
  //       Color: "Space Gray",
  //       Storage: "64 GB",
  //       Model: ["MWEV2"],
  //     },
  //     {
  //       Color: "Space Gray",
  //       Storage: "256 GB",
  //       Model: ["MWF12"],
  //     },
  //     {
  //       Color: "Space Gray",
  //       Storage: "512 GB",
  //       Model: ["MWF52"],
  //     },
  //   ],
  // },
  // {
  //   Generation: "iPhone SE (2nd generation)",
  //   ANumber: ["A2275", "A2296", "A2298"],
  //   Bootrom: "Bootrom 4479.0.0.100.4",
  //   FCCID: ["E3500A", "E3501A"],
  //   InternalName: "D79AP",
  //   Identifier: "iPhone12,8",
  //   Models: [
  //     {
  //       Color: "White",
  //       Storage: "64 GB",
  //       Model: [
  //         "MX9T2",
  //         "MX9A2",
  //         "MX9H2",
  //         "MX9E2",
  //         "MX9L2",
  //         "MX9P2",
  //         "MXAN2",
  //         "MHGQ3",
  //       ],
  //     },
  //     {
  //       Color: "White",
  //       Storage: "128 GB",
  //       Model: [
  //         "MXD12",
  //         "MXCJ2",
  //         "MXCQ2",
  //         "MXCM2",
  //         "MXCU2",
  //         "MXCX2",
  //         "MXD72",
  //         "MHGU3",
  //       ],
  //     },
  //     {
  //       Color: "White",
  //       Storage: "256 GB",
  //       Model: [
  //         "MXVU2",
  //         "MXVC2",
  //         "MXVJ2",
  //         "MXVF2",
  //         "MXVM2",
  //         "MXVQ2",
  //         "MXW12",
  //         "MHGX3",
  //       ],
  //     },
  //     {
  //       Color: "Black",
  //       Storage: "64 GB",
  //       Model: [
  //         "MX9R2",
  //         "MX992",
  //         "MX9G2",
  //         "MX9D2",
  //         "MX9K2",
  //         "MX9N2",
  //         "MXAM2",
  //         "MHGP3",
  //       ],
  //     },
  //     {
  //       Color: "Black",
  //       Storage: "128 GB",
  //       Model: [
  //         "MXD02",
  //         "MXCH2",
  //         "MXCP2",
  //         "MXCL2",
  //         "MXCT2",
  //         "MXCW2",
  //         "MXD62",
  //         "MHGT3",
  //       ],
  //     },
  //     {
  //       Color: "Black",
  //       Storage: "256 GB",
  //       Model: [
  //         "MXVT2",
  //         "MXVA2",
  //         "MXVH2",
  //         "MXVE2",
  //         "MXVL2",
  //         "MXVP2",
  //         "MXW02",
  //         "MHGW3",
  //       ],
  //     },
  //     {
  //       Color: "Red",
  //       Storage: "64 GB",
  //       Model: [
  //         "MX9U2",
  //         "MX9C2",
  //         "MX9J2",
  //         "MX9F2",
  //         "MX9M2",
  //         "MX9Q2",
  //         "MXAP2",
  //         "MHGR3",
  //       ],
  //     },
  //     {
  //       Color: "Red",
  //       Storage: "128 GB",
  //       Model: ["MXD22", "MXCK2", "MXCR2", "MXCN2", "MXCV2", "MXCY2", "MXD82"],
  //     },
  //     {
  //       Color: "Red",
  //       Storage: "256 GB",
  //       Model: [
  //         "MXVV2",
  //         "MXVD2",
  //         "MXVK2",
  //         "MXVG2",
  //         "MXVN2",
  //         "MXVR2",
  //         "MXW22",
  //         "MHGY3",
  //       ],
  //     },
  //   ],
  // },
  // {
  //   Generation: "iPhone 12 mini",
  //   ANumber: ["A2176", "A2398", "A2400", "A2399"],
  //   Bootrom: "Bootrom 5281.0.0.100.45",
  //   FCCID: ["BCG-E3539A"],
  //   InternalName: "D52gAP",
  //   Identifier: "iPhone13,1",
  //   Models: [
  //     {
  //       Color: "White",
  //       Storage: "64 GB",
  //       Model: [
  //         "MG803",
  //         "MGDY3",
  //         "MG613",
  //         "MG7H3",
  //         "MG713",
  //         "MG6H3",
  //         "MG8G3",
  //         "MGA63",
  //       ],
  //     },
  //     {
  //       Color: "White",
  //       Storage: "128 GB",
  //       Model: [
  //         "MG853",
  //         "MGE43",
  //         "MG8M3",
  //         "MG663",
  //         "MG7N3",
  //         "MG763",
  //         "MG6N3",
  //         "MGDM3",
  //       ],
  //     },
  //     {
  //       Color: "White",
  //       Storage: "256 GB",
  //       Model: [
  //         "MG8A3",
  //         "MGEA3",
  //         "MG6C3",
  //         "MG7U3",
  //         "MG7C3",
  //         "MG6V3",
  //         "MG8T3",
  //         "MGDT3",
  //       ],
  //     },
  //     {
  //       Color: "Black",
  //       Storage: "64 GB",
  //       Model: [
  //         "MG7Y3",
  //         "MGDX3",
  //         "MG603",
  //         "MG7G3",
  //         "MG703",
  //         "MG6G3",
  //         "MG8F3",
  //         "MGA03",
  //       ],
  //     },
  //     {
  //       Color: "Black",
  //       Storage: "128 GB",
  //       Model: [
  //         "MG843",
  //         "MGE33",
  //         "MG653",
  //         "MG7M3",
  //         "MG753",
  //         "MG6M3",
  //         "MG8L3",
  //         "MGDJ3",
  //       ],
  //     },
  //     {
  //       Color: "Black",
  //       Storage: "256 GB",
  //       Model: [
  //         "MG893C",
  //         "MGE93",
  //         "MG8R3",
  //         "MG6A3",
  //         "MG7T3",
  //         "MG7A3",
  //         "MG6U3",
  //         "MGDR3",
  //       ],
  //     },
  //     {
  //       Color: "Red",
  //       Storage: "64 GB",
  //       Model: [
  //         "MG813",
  //         "MGE03",
  //         "MG623",
  //         "MG7J3",
  //         "MG723",
  //         "MG6J3",
  //         "MG8H3",
  //         "MGAE3",
  //       ],
  //     },
  //     {
  //       Color: "Red",
  //       Storage: "128 GB",
  //       Model: [
  //         "MG863",
  //         "MGE53",
  //         "MG8N3",
  //         "MG673",
  //         "MG7P3",
  //         "MG6P3",
  //         "MG773",
  //         "MGDN3",
  //       ],
  //     },
  //     {
  //       Color: "Red",
  //       Storage: "256 GB",
  //       Model: [
  //         "MG8C3",
  //         "MGEC3",
  //         "MG6D3",
  //         "MG7V3",
  //         "MG7D3",
  //         "MG6W3",
  //         "MG8U3",
  //         "MGDU3",
  //       ],
  //     },
  //     {
  //       Color: "Green",
  //       Storage: "64 GB",
  //       Model: [
  //         "MG833",
  //         "MGE23",
  //         "MG8K3",
  //         "MG643",
  //         "MG7L3",
  //         "MG743",
  //         "MG6L3",
  //         "MGAV3",
  //       ],
  //     },
  //     {
  //       Color: "Green",
  //       Storage: "128 GB",
  //       Model: [
  //         "MG883",
  //         "MGE73",
  //         "MG693",
  //         "MG7R3",
  //         "MG793",
  //         "MG6T3",
  //         "MG8Q3",
  //         "MGDQ3",
  //       ],
  //     },
  //     {
  //       Color: "Green",
  //       Storage: "256 GB",
  //       Model: [
  //         "MG8E3",
  //         "MGEE3",
  //         "MG8W3",
  //         "MG6F3",
  //         "MG7X3",
  //         "MG7F3",
  //         "MG6Y3",
  //         "MGDW3",
  //       ],
  //     },
  //     {
  //       Color: "Blue",
  //       Storage: "64 GB",
  //       Model: [
  //         "MG823",
  //         "MGE13",
  //         "MG8J3",
  //         "MG633",
  //         "MG7K3",
  //         "MG733",
  //         "MG6K3",
  //         "MGAP3",
  //       ],
  //     },
  //     {
  //       Color: "Blue",
  //       Storage: "128 GB",
  //       Model: [
  //         "MG873",
  //         "MGE63",
  //         "MG683",
  //         "MG7Q3",
  //         "MG783",
  //         "MG6Q3",
  //         "MG8P3",
  //         "MGDP3",
  //       ],
  //     },
  //     {
  //       Color: "Blue",
  //       Storage: "256 GB",
  //       Model: [
  //         "MG8D3",
  //         "MGED3",
  //         "MG6E3",
  //         "MG7W3",
  //         "MG7E3",
  //         "MG6X3",
  //         "MG8V3",
  //         "MGDV3",
  //       ],
  //     },
  //     {
  //       Color: "Purple",
  //       Storage: "64 GB",
  //       Model: [
  //         "MJNL3",
  //         "MJQ23",
  //         "MJNY3",
  //         "MJNT3",
  //         "MJQ83",
  //         "MJQF3",
  //         "MJQ53",
  //         "MJQC3",
  //       ],
  //     },
  //     {
  //       Color: "Purple",
  //       Storage: "128 GB",
  //       Model: [
  //         "MJQ93",
  //         "MJNN3",
  //         "MJQ33",
  //         "MJQ03",
  //         "MJNW3",
  //         "MJQG3",
  //         "MJQ63",
  //         "MJQD3",
  //       ],
  //     },
  //     {
  //       Color: "Purple",
  //       Storage: "256 GB",
  //       Model: [
  //         "MJNR3",
  //         "MJQ43",
  //         "MJQ13",
  //         "MJNX3",
  //         "MJQA3",
  //         "MJQH3",
  //         "MJQ73",
  //         "MJQE3",
  //       ],
  //     },
  //   ],
  // },
  // {
  //   Generation: "iPhone 12",
  //   ANumber: ["A2172", "A2402", "A2404", "A2403"],
  //   Bootrom: "Bootrom 5281.0.0.100.45",
  //   FCCID: ["BCG-E3542A"],
  //   InternalName: "D53gAP",
  //   Identifier: "iPhone13,2",
  //   Models: [
  //     {
  //       Color: "White",
  //       Storage: "64 GB",
  //       Model: [
  //         "MGGN3",
  //         "MGJ63",
  //         "MGEG3",
  //         "MGG63",
  //         "MGFM3",
  //         "MGF53",
  //         "MGH73",
  //         "MGHP3",
  //       ],
  //     },
  //     {
  //       Color: "White",
  //       Storage: "128 GB",
  //       Model: [
  //         "MGGV3",
  //         "MGJC3",
  //         "MGHD3",
  //         "MGET3",
  //         "MGGC3",
  //         "MGFT3",
  //         "MGFA3",
  //         "MGHV3",
  //       ],
  //     },
  //     {
  //       Color: "White",
  //       Storage: "256 GB",
  //       Model: [
  //         "MGH23",
  //         "MGJH3",
  //         "MGF03",
  //         "MGGH3",
  //         "MGG13",
  //         "MGFG3",
  //         "MGHJ3",
  //         "MGJ13",
  //       ],
  //     },
  //     {
  //       Color: "Black",
  //       Storage: "64 GB",
  //       Model: [
  //         "MGGM3",
  //         "MGJ53",
  //         "MGEF3",
  //         "MGG53",
  //         "MGFL3",
  //         "MGF43",
  //         "MGH63",
  //         "MGHN3",
  //       ],
  //     },
  //     {
  //       Color: "Black",
  //       Storage: "128 GB",
  //       Model: [
  //         "MGGU3",
  //         "MGJA3",
  //         "MGHC3",
  //         "MGER3",
  //         "MGGA3",
  //         "MGFR3",
  //         "MGF93",
  //         "MGHU3",
  //       ],
  //     },
  //     {
  //       Color: "Black",
  //       Storage: "256 GB",
  //       Model: [
  //         "MGH13",
  //         "MGJG3",
  //         "MGHH3",
  //         "MGEX3",
  //         "MGGG3",
  //         "MGG03",
  //         "MGFF3",
  //         "MGJ03",
  //       ],
  //     },
  //     {
  //       Color: "Red",
  //       Storage: "64 GB",
  //       Model: [
  //         "MGGP3",
  //         "MGJ73",
  //         "MGEH3",
  //         "MGG73",
  //         "MGFN3",
  //         "MGF63",
  //         "MGH83",
  //         "MGHQ3",
  //       ],
  //     },
  //     {
  //       Color: "Red",
  //       Storage: "128 GB",
  //       Model: [
  //         "MGGW3",
  //         "MGJD3",
  //         "MGHE3",
  //         "MGEU3",
  //         "MGGD3",
  //         "MGFW3",
  //         "MGFC3",
  //         "MGHW3",
  //       ],
  //     },
  //     {
  //       Color: "Red",
  //       Storage: "256 GB",
  //       Model: [
  //         "MGH33",
  //         "MGJJ3",
  //         "MGF13",
  //         "MGGJ3",
  //         "MGG23",
  //         "MGFH3",
  //         "MGHK3",
  //         "MGJ23",
  //       ],
  //     },
  //     {
  //       Color: "Green",
  //       Storage: "64 GB",
  //       Model: [
  //         "MGGT3",
  //         "MGJ93",
  //         "MGEQ3",
  //         "MGG93",
  //         "MGFQ3",
  //         "MGF83",
  //         "MGHA3",
  //         "MGHT3",
  //       ],
  //     },
  //     {
  //       Color: "Green",
  //       Storage: "128 GB",
  //       Model: [
  //         "MGGY3",
  //         "MGJF3",
  //         "MGHG3",
  //         "MGEW3",
  //         "MGGF3",
  //         "MGFY3",
  //         "MGFE3",
  //         "MGHY3",
  //       ],
  //     },
  //     {
  //       Color: "Green",
  //       Storage: "256 GB",
  //       Model: [
  //         "MGH53",
  //         "MGJL3",
  //         "MGHM3",
  //         "MGF33",
  //         "MGGL3",
  //         "MGG43",
  //         "MGFK3",
  //         "MGJ43",
  //       ],
  //     },
  //     {
  //       Color: "Blue",
  //       Storage: "64 GB",
  //       Model: [
  //         "MGGQ3",
  //         "MGJ83",
  //         "MGH93",
  //         "MGEK3",
  //         "MGG83",
  //         "MGFP3",
  //         "MGF73",
  //         "MGHR3",
  //       ],
  //     },
  //     {
  //       Color: "Blue",
  //       Storage: "128 GB",
  //       Model: [
  //         "MGGX3",
  //         "MGJE3",
  //         "MGEV3",
  //         "MGGE3",
  //         "MGFX3",
  //         "MGFD3",
  //         "MGHF3",
  //         "MGHX3",
  //       ],
  //     },
  //     {
  //       Color: "Blue",
  //       Storage: "256 GB",
  //       Model: [
  //         "MGH43",
  //         "MGJK3",
  //         "MGF23",
  //         "MGGK3",
  //         "MGG33",
  //         "MGFJ3",
  //         "MGHL3",
  //         "MGJ33",
  //       ],
  //     },
  //     {
  //       Color: "Purple",
  //       Storage: "64 GB",
  //       Model: [
  //         "MJMX3",
  //         "MJN73",
  //         "MJN43",
  //         "MJN13",
  //         "MJNE3",
  //         "MJNM3",
  //         "MJNA3",
  //         "MJNH3",
  //       ],
  //     },
  //     {
  //       Color: "Purple",
  //       Storage: "128 GB",
  //       Model: [
  //         "MJNF3",
  //         "MJMY3",
  //         "MJN83",
  //         "MJN53",
  //         "MJN23",
  //         "MJNP3",
  //         "MJNC3",
  //         "MJNJ3",
  //       ],
  //     },
  //     {
  //       Color: "Purple",
  //       Storage: "256 GB",
  //       Model: [
  //         "MJN03",
  //         "MJN93",
  //         "MJN63",
  //         "MJN33",
  //         "MJNG3",
  //         "MJNQ3",
  //         "MJND3",
  //         "MJNK3",
  //       ],
  //     },
  //   ],
  // },
  // {
  //   Generation: "iPhone 12 Pro",
  //   ANumber: ["A2341", "A2406", "A2407", "A2408"],
  //   Bootrom: "Bootrom 5281.0.0.100.45",
  //   FCCID: ["BCG-E3545A"],
  //   InternalName: "D53pAP",
  //   Identifier: "iPhone13,3",
  //   Models: [
  //     {
  //       Color: "Silver",
  //       Storage: "128 GB",
  //       Model: [
  //         "MGLA3",
  //         "MGML3",
  //         "MGJN3",
  //         "MGKW3",
  //         "MGKH3",
  //         "MGK23",
  //         "MGLP3",
  //         "MGM63",
  //       ],
  //     },
  //     {
  //       Color: "Silver",
  //       Storage: "256 GB",
  //       Model: [
  //         "MGLF3",
  //         "MGMQ3",
  //         "MGLU3",
  //         "MGJT3",
  //         "MGL23",
  //         "MGKM3",
  //         "MGK63",
  //         "MGMA3",
  //       ],
  //     },
  //     {
  //       Color: "Silver",
  //       Storage: "512 GB",
  //       Model: [
  //         "MGLK3",
  //         "MGMV3",
  //         "MGJX3",
  //         "MGL63",
  //         "MGKR3",
  //         "MGKC3",
  //         "MGLY3",
  //         "MGMG3",
  //       ],
  //     },
  //     {
  //       Color: "Graphite",
  //       Storage: "128 GB",
  //       Model: [
  //         "MGL93",
  //         "MGMK3",
  //         "MGJM3",
  //         "MGKV3",
  //         "MGKG3",
  //         "MGK13",
  //         "MGLN3",
  //         "MGM53",
  //       ],
  //     },
  //     {
  //       Color: "Graphite",
  //       Storage: "256 GB",
  //       Model: [
  //         "MGLE3",
  //         "MGMP3",
  //         "MGLT3",
  //         "MGJR3",
  //         "MGKL3",
  //         "MGK53",
  //         "MGL03",
  //         "MGM93",
  //       ],
  //     },
  //     {
  //       Color: "Graphite",
  //       Storage: "512 GB",
  //       Model: [
  //         "MGLJ3",
  //         "MGMU3",
  //         "MGLX3",
  //         "MGJW3",
  //         "MGL53",
  //         "MGKQ3",
  //         "MGKA3",
  //         "MGMF3",
  //       ],
  //     },
  //     {
  //       Color: "Gold",
  //       Storage: "128 GB",
  //       Model: [
  //         "MGLC3",
  //         "MGMM3",
  //         "MGJP3",
  //         "MGKX3",
  //         "MGKJ3",
  //         "MGK33",
  //         "MGLQ3",
  //         "MGM73",
  //       ],
  //     },
  //     {
  //       Color: "Gold",
  //       Storage: "256 GB",
  //       Model: [
  //         "MGLG3",
  //         "MGMR3",
  //         "MGJU3",
  //         "MGL33",
  //         "MGKN3",
  //         "MGK73",
  //         "MGLV3",
  //         "MGMC3",
  //       ],
  //     },
  //     {
  //       Color: "Gold",
  //       Storage: "512 GB",
  //       Model: [
  //         "MGLL3",
  //         "MGMW3",
  //         "MGM23",
  //         "MGJY3",
  //         "MGL73",
  //         "MGKT3",
  //         "MGKE3",
  //         "MGMH3",
  //       ],
  //     },
  //     {
  //       Color: "Pacific Blue",
  //       Storage: "128 GB",
  //       Model: [
  //         "MGLD3",
  //         "MGMN3",
  //         "MGJQ3",
  //         "MGKY3",
  //         "MGKK3",
  //         "MGK43",
  //         "MGLR3",
  //         "MGM83",
  //       ],
  //     },
  //     {
  //       Color: "Pacific Blue",
  //       Storage: "256 GB",
  //       Model: [
  //         "MGLH3",
  //         "MGMT3",
  //         "MGJV3",
  //         "MGL43",
  //         "MGKP3",
  //         "MGK93",
  //         "MGLW3",
  //         "MGMD3",
  //       ],
  //     },
  //     {
  //       Color: "Pacific Blue",
  //       Storage: "512 GB",
  //       Model: [
  //         "MGLM3",
  //         "MGMX3",
  //         "MGK03",
  //         "MGL83",
  //         "MGKU3",
  //         "MGKF3",
  //         "MGM43",
  //         "MGMJ3",
  //       ],
  //     },
  //   ],
  // },
  // {
  //   Generation: "iPhone 12 Pro Max",
  //   ANumber: ["A2342", "A2410", "A2411", "A2412"],
  //   Bootrom: "Bootrom 5281.0.0.100.45",
  //   FCCID: ["BCG-E3548A"],
  //   InternalName: "D54pAP",
  //   Identifier: "iPhone13,4",
  //   Models: [
  //     {
  //       Color: "Silver",
  //       Storage: "128 GB",
  //       Model: [
  //         "MGC13",
  //         "MGD83",
  //         "MG8Y3",
  //         "MGA93",
  //         "MG9Q3",
  //         "MG9C3",
  //         "MGCG3",
  //         "MGCV3",
  //       ],
  //     },
  //     {
  //       Color: "Silver",
  //       Storage: "256 GB",
  //       Model: [
  //         "MGC53",
  //         "MGDD3",
  //         "MGCL3",
  //         "MG933",
  //         "MGAJ3",
  //         "MG9V3",
  //         "MG9G3",
  //         "MGD03",
  //       ],
  //     },
  //     {
  //       Color: "Silver",
  //       Storage: "512 GB",
  //       Model: [
  //         "MGCA3",
  //         "MGDH3",
  //         "MG973",
  //         "MGAU3",
  //         "MGA23",
  //         "MG9L3",
  //         "MGCQ3",
  //         "MGD43",
  //       ],
  //     },
  //     {
  //       Color: "Graphite",
  //       Storage: "128 GB",
  //       Model: [
  //         "MGC03",
  //         "MGD73",
  //         "MG8X3",
  //         "MGA73",
  //         "MG9P3",
  //         "MG9A3",
  //         "MGCF3",
  //         "MGCU3",
  //       ],
  //     },
  //     {
  //       Color: "Graphite",
  //       Storage: "256 GB",
  //       Model: [
  //         "MGC43",
  //         "MGDC3",
  //         "MGCK3",
  //         "MG923",
  //         "MGAH3",
  //         "MG9U3",
  //         "MG9F3",
  //         "MGCY3",
  //       ],
  //     },
  //     {
  //       Color: "Graphite",
  //       Storage: "512 GB",
  //       Model: [
  //         "MGC93",
  //         "MGDG3",
  //         "MGCP3",
  //         "MG963",
  //         "MGAR3",
  //         "MG9Y3",
  //         "MG9K3",
  //         "MGD33",
  //       ],
  //     },
  //     {
  //       Color: "Gold",
  //       Storage: "128 GB",
  //       Model: [
  //         "MGC23",
  //         "MGD93",
  //         "MG903",
  //         "MGAA3",
  //         "MG9R3",
  //         "MG9D3",
  //         "MGCH3",
  //         "MGCW3",
  //       ],
  //     },
  //     {
  //       Color: "Gold",
  //       Storage: "256 GB",
  //       Model: [
  //         "MGC63",
  //         "MGDE3",
  //         "MG943",
  //         "MGAM3",
  //         "MG9W3",
  //         "MG9H3",
  //         "MGCM3",
  //         "MGD13",
  //       ],
  //     },
  //     {
  //       Color: "Gold",
  //       Storage: "512 GB",
  //       Model: [
  //         "MGCC3",
  //         "MGDK3",
  //         "MGCR3",
  //         "MG983",
  //         "MGAW3",
  //         "MGA33",
  //         "MG9M3",
  //         "MGD53",
  //       ],
  //     },
  //     {
  //       Color: "Pacific Blue",
  //       Storage: "128 GB",
  //       Model: [
  //         "MGC33",
  //         "MGDA3",
  //         "MGCJ3",
  //         "MG913",
  //         "MGAF3",
  //         "MG9T3",
  //         "MG9E3",
  //         "MGCX3",
  //       ],
  //     },
  //     {
  //       Color: "Pacific Blue",
  //       Storage: "256 GB",
  //       Model: [
  //         "MGC73",
  //         "MGDF3",
  //         "MG953",
  //         "MGAQ3",
  //         "MG9X3",
  //         "MG9J3",
  //         "MGCN3",
  //         "MGD23",
  //       ],
  //     },
  //     {
  //       Color: "Pacific Blue",
  //       Storage: "512 GB",
  //       Model: [
  //         "MGCE3",
  //         "MGDL3",
  //         "MG993",
  //         "MGAX3",
  //         "MGA43",
  //         "MG9N3",
  //         "MGCT3",
  //         "MGD63",
  //       ],
  //     },
  //   ],
  // },
  // {
  //   Generation: "iPhone 13 mini",
  //   ANumber: ["A2481", "A2626", "A2629", "A2630", "A2628"],
  //   Bootrom: "Bootrom 6338.0.0.200.19",
  //   FCCID: [],
  //   InternalName: "D16AP",
  //   Identifier: "iPhone14,4",
  //   Models: [
  //     {
  //       Color: "Red",
  //       Storage: "128 GB",
  //       Model: ["MLK33", "MLHQ3", "MLDF3"],
  //     },
  //     {
  //       Color: "Red",
  //       Storage: "256 GB",
  //       Model: ["MLK83", "MLHW3", "MLDL3"],
  //     },
  //     {
  //       Color: "Red",
  //       Storage: "512 GB",
  //       Model: ["MLKE3", "MLJ23", "MLDR3"],
  //     },
  //     {
  //       Color: "Starlight",
  //       Storage: "128 GB",
  //       Model: ["MLK13", "MLHN3", "MLDD3"],
  //     },
  //     {
  //       Color: "Starlight",
  //       Storage: "256 GB",
  //       Model: ["MLK63", "MLHU3", "MLDJ3"],
  //     },
  //     {
  //       Color: "Starlight",
  //       Storage: "512 GB",
  //       Model: ["MLKC3", "MLJ03", "MLDP3"],
  //     },
  //     {
  //       Color: "Midnight",
  //       Storage: "128 GB",
  //       Model: ["MLK03", "MLHM3", "MLDC3"],
  //     },
  //     {
  //       Color: "Midnight",
  //       Storage: "256 GB",
  //       Model: ["MLK53", "MLHT3", "MLDH3"],
  //     },
  //     {
  //       Color: "Midnight",
  //       Storage: "512 GB",
  //       Model: ["MLKA3", "MLHY3", "MLDN3"],
  //     },
  //     {
  //       Color: "Blue",
  //       Storage: "128 GB",
  //       Model: ["MLK43", "MLHR3", "MLDG3"],
  //     },
  //     {
  //       Color: "Blue",
  //       Storage: "256 GB",
  //       Model: ["MLK93", "MLHX3", "MLDM3"],
  //     },
  //     {
  //       Color: "Blue",
  //       Storage: "512 GB",
  //       Model: ["MLKF3", "MLJ33", "MLDT3"],
  //     },
  //     {
  //       Color: "Pink",
  //       Storage: "128 GB",
  //       Model: ["MLK23", "MLHP3", "MLDE3"],
  //     },
  //     {
  //       Color: "Pink",
  //       Storage: "256 GB",
  //       Model: ["MLK73", "MLHV3", "MLDK3"],
  //     },
  //     {
  //       Color: "Pink",
  //       Storage: "512 GB",
  //       Model: ["MLKD3", "MLJ13", "MLDQ3"],
  //     },
  //     {
  //       Color: "Green",
  //       Storage: "128 GB",
  //       Model: ["MNF83", "MNF53", "MNFF3"],
  //     },
  //     {
  //       Color: "Green",
  //       Storage: "256 GB",
  //       Model: ["MNF93", "MNF63", "MNFG3"],
  //     },
  //     {
  //       Color: "Green",
  //       Storage: "512 GB",
  //       Model: ["MNFA3", "MNF73", "MNFH3"],
  //     },
  //   ],
  // },

  {
    productId: "iPhone15-Plus-2024-Blue",
    brand: "Apple",
    Generation: "iPhone 15 Plus",
    title: "Apple iPhone 15 Plus (Blue, 128 GB)",
    imageURLLarge: "https://rb.gy/5hr30q",
    spec: [
      "128 GB ROM",
      "17.02 cm (6.7 inch) Super Retina XDR Display",
      "48MP + 12MP | 12MP Front Camera",
      "A16 Bionic Chip, 6 Core Processor Processor",
      " 1 Year Manufacturer Warranty For Device And 6 Months Manufacturer Warranty For In-Box Accessories",
    ],
    price: "74,999",
    colors: ["Blue", "Black", "Green"],
    deliveryCost: "Free",

    Identifier: "iPhone14,2",
    Models: [
      {
        Color: "Graphite",
        Storage: "128 GB",
        Model: ["MLV93", "MLTP3", "MLT53"],
      },
      {
        Color: "Graphite",
        Storage: "256 GB",
        Model: ["MLVE3", "MLTW3", "MLT93"],
      },
      {
        Color: "Graphite",
        Storage: "512 GB",
        Model: ["MLVH3", "MLU13", "MLTF3"],
      },
      {
        Color: "Graphite",
        Storage: "1 TB",
        Model: ["MLVV3", "MLU93", "MLTK3"],
      },
      {
        Color: "Gold",
        Storage: "128 GB",
        Model: ["MLVC3", "MLTR3", "MLT73"],
      },
      {
        Color: "Gold",
        Storage: "256 GB",
        Model: ["MLVK3", "MLTY3", "MLTH3"],
      },
      {
        Color: "Gold",
        Storage: "512 GB",
        Model: ["MLVQ3", "MLU43", "MLTH3"],
      },
      {
        Color: "Gold",
        Storage: "1 TB",
        Model: ["MLVY3", "MLUC3", "MLTM3"],
      },
      {
        Color: "Silver",
        Storage: "128 GB",
        Model: ["MLVA3", "MLTQ3", "MLT63"],
      },
      {
        Color: "Silver",
        Storage: "256 GB",
        Model: ["MLVF3", "MLTX3", "MLTC3"],
      },
      {
        Color: "Silver",
        Storage: "512 GB",
        Model: ["MLVN3", "MLU33", "MLTG3"],
      },
      {
        Color: "Silver",
        Storage: "1 TB",
        Model: ["MLVW3", "MLUA3", "MLTL3"],
      },
      {
        Color: "Sierra Blue",
        Storage: "128 GB",
        Model: ["MLVD3", "MLTT3", "MLT83"],
      },
      {
        Color: "Sierra Blue",
        Storage: "256 GB",
        Model: ["MLVP3", "MLU03", "MLTE3"],
      },
      {
        Color: "Sierra Blue",
        Storage: "512 GB",
        Model: ["MLVU3", "MLU73", "MLTJ3"],
      },
      {
        Color: "Sierra Blue",
        Storage: "1 TB",
        Model: ["MLW03", "MLUD3", "MLTN3"],
      },
      {
        Color: "Alpine Green",
        Storage: "128 GB",
        Model: ["MNDT3", "MNDN3", "MNE23"],
      },
      {
        Color: "Alpine Green",
        Storage: "256 GB",
        Model: ["MNDU3", "MNDP3", "MNE33"],
      },
      {
        Color: "Alpine Green",
        Storage: "512 GB",
        Model: ["MNDV3", "MNDQ3", "MNE43"],
      },
      {
        Color: "Alpine Green",
        Storage: "1 TB",
        Model: ["MNDW3", "MNDR3", "MNE53"],
      },
    ],
  },
  {
    productId: "iPhone15-Pro-2024-White_Titanium",
    brand: "Apple",
    Generation: "iPhone 15 Pro",
    title: "Apple iPhone 15 Pro (White Titanium, 128 GB)",
    imageURLLarge: "https://rb.gy/jx59se",
    spec: [
      "128 GB ROM",
      "15.49 cm (6.1 inch) Super Retina XDR Display",
      "48MP + 12MP + 12MP | 12MP Front Camera",
      "A17 Pro Chip, 6 Core Processor Processor",
      " 1 Year Manufacturer Warranty For Device And 6 Months Manufacturer Warranty For In-Box Accessories",
    ],
    deliveryCost: "Free",
    price: "1,19,900",
    colors: ["White Titanium", "Black Titanium", "Blue Titanium"],

    Models: [
      {
        Color: "Graphite",
        Storage: "128 GB",
        Model: ["MLL63", "MLKL3", "MLH43"],
      },
      {
        Color: "Graphite",
        Storage: "256 GB",
        Model: ["MLLA3", "MLKR3", "MLH83"],
      },
      {
        Color: "Graphite",
        Storage: "512 GB",
        Model: ["MLLF3", "MLKW3", "MLHD3"],
      },
      {
        Color: "Graphite",
        Storage: "1 TB",
        Model: ["MLLK3", "MLL23", "MLHH3"],
      },
      {
        Color: "Gold",
        Storage: "128 GB",
        Model: ["MLL83", "MLKN3", "MLH63"],
      },
      {
        Color: "Gold",
        Storage: "256 GB",
        Model: ["MLLD3", "MLKU3", "MLHA3"],
      },
      {
        Color: "Gold",
        Storage: "512 GB",
        Model: ["MLLH3", "MLKY3", "MLHF3"],
      },
      {
        Color: "Gold",
        Storage: "1 TB",
        Model: ["MLLM3", "MLL43", "MLHK3"],
      },
      {
        Color: "Silver",
        Storage: "128 GB",
        Model: ["MLL73", "MLKM3", "MLH53"],
      },
      {
        Color: "Silver",
        Storage: "256 GB",
        Model: ["MLLC3", "MLKT3", "MLH93"],
      },
      {
        Color: "Silver",
        Storage: "512 GB",
        Model: ["MLLG3", "MLKX3", "MLHE3"],
      },
      {
        Color: "Silver",
        Storage: "1 TB",
        Model: ["MLLL3", "MLL33", "MLHJ3"],
      },
      {
        Color: "Sierra Blue",
        Storage: "128 GB",
        Model: ["MLL93", "MLKP3", "MLH73"],
      },
      {
        Color: "Sierra Blue",
        Storage: "256 GB",
        Model: ["MLLE3", "MLKV3", "MLHC3"],
      },
      {
        Color: "Sierra Blue",
        Storage: "512 GB",
        Model: ["MLLJ3", "MLL03", "MLHG3"],
      },
      {
        Color: "Sierra Blue",
        Storage: "1 TB",
        Model: ["MLLN3", "MLL53", "MLHL3"],
      },
      {
        Color: "Alpine Green",
        Storage: "128 GB",
        Model: ["MNCP3", "MNCK3", "MNCY3"],
      },
      {
        Color: "Alpine Green",
        Storage: "256 GB",
        Model: ["MNCQ3", "MNCL3", "MND03"],
      },
      {
        Color: "Alpine Green",
        Storage: "512 GB",
        Model: ["MNCR3", "MNCM3", "MND13"],
      },
      {
        Color: "Alpine Green",
        Storage: "1 TB",
        Model: ["MNCT3", "MNCN3", "MND23"],
      },
    ],
  },
  {
    productId: "iPhone15-Pro-Max-2024-Space_Black",
    brand: "Apple",
    Generation: "iPhone 15 Pro Max",
    title: "Apple iPhone 15 Pro Max (Space Black, 128 GB)",
    imageURLLarge: "https://rb.gy/7vp06e",
    deliveryCost: "Free",
    spec: [
      "256 GB ROM",
      "17.02 cm (6.7 inch) Super Retina XDR Display",
      "48MP + 12MP + 12MP | 12MP Front Camera",
      "A17 Pro Chip, 6 Core Processor Processor",
      " 1 Year Manufacturer Warranty For Device And 6 Months Manufacturer Warranty For In-Box Accessories",
    ],
    price: "1,67,900",
    colors: ["Space Black", "Silver", "Yellow", "Deep Purple"],

    FCCID: ["BCG-E4082A", "BCG-E8064A", "BCG-E4083A", "BCG-E8076A"],
    InternalName: "D49AP",
    Identifier: "iPhone14,6",
    Models: [
      {
        Color: "Midnight",
        Storage: "64 GB",
        Model: ["MMX53", "MMWV3", "MMXF3", "MMYC3"],
      },
      {
        Color: "Midnight",
        Storage: "128 GB",
        Model: ["MMX83", "MMWY3", "MMXJ3", "MMYF3"],
      },
      {
        Color: "Midnight",
        Storage: "256 GB",
        Model: ["MMXC3", "MMX23", "MMXM3", "MMYJ3"],
      },
      {
        Color: "Starlight",
        Storage: "64 GB",
        Model: ["MMX63", "MMWW3", "MMXG3", "MMYD3"],
      },
      {
        Color: "Starlight",
        Storage: "128 GB",
        Model: ["MMX93", "MMX03", "MMXK3", "MMYG3"],
      },
      {
        Color: "Starlight",
        Storage: "256 GB",
        Model: ["MMXD3", "MMX33", "MMXN3", "MMYK3"],
      },
      {
        Color: "Red",
        Storage: "64 GB",
        Model: ["MMX73", "MMWX3", "MMXH3", "MMYE3"],
      },
      {
        Color: "Red",
        Storage: "128 GB",
        Model: ["MMXA3", "MMX13", "MMXL3", "MMYH3"],
      },
      {
        Color: "Red",
        Storage: "256 GB",
        Model: ["MMXE3", "MMX43", "MMXP3", "MMYL3"],
      },
    ],
  },
  {
    productId: "iPhone15-2024-Blue",
    brand: "Apple",
    Generation: "iPhone 15",
    title: "Apple iPhone 15 (Blue, 128 GB)",
    imageURLLarge: "http://tiny.cc/fifneet",
    deliveryCost: "Free",
    spec: [
      "128 GB ROM",
      "15.49 cm (6.1 inch) Super Retina XDR Display",
      "48MP + 12MP | 12MP Front Camera",
      "A16 Bionic Chip, 6 Core Processor Processor",
      " 1 Year Manufacturer Warranty For Device And 6 Months Manufacturer Warranty For In-Box Accessories",
    ],
    price: "66,999",
    colors: ["Black", "Blue", "Green", "Yellow", "Green"],

    Models: [
      {
        Color: "Red",
        Storage: "128 GB",
        Model: ["MLPJ3", "MLMQ3", "MLDX3"],
      },
      {
        Color: "Red",
        Storage: "256 GB",
        Model: ["MLQ93", "MLN03", "MLE33"],
      },
      {
        Color: "Red",
        Storage: "512 GB",
        Model: ["MLQF3", "MLN53", "MLEA3"],
      },
      {
        Color: "Starlight",
        Storage: "128 GB",
        Model: ["MLPG3", "MLMM3", "MLDV3"],
      },
      {
        Color: "Starlight",
        Storage: "256 GB",
        Model: ["MLQ73", "MLMX3", "MLE13"],
      },
      {
        Color: "Starlight",
        Storage: "512 GB",
        Model: ["MLQD3", "MLN33", "MLE73"],
      },
      {
        Color: "Midnight",
        Storage: "128 GB",
        Model: ["MLPF3", "MLML3", "MLDU3"],
      },
      {
        Color: "Midnight",
        Storage: "256 GB",
        Model: ["MLQ63", "MLN23", "MLE03"],
      },
      {
        Color: "Midnight",
        Storage: "512 GB",
        Model: ["MLQC3", "MLN23", "MLE63"],
      },
      {
        Color: "Blue",
        Storage: "128 GB",
        Model: ["MLPK3", "MLMT3", "MLDY3"],
      },
      {
        Color: "Blue",
        Storage: "256 GB",
        Model: ["MLQA3", "MLN13", "MLE43"],
      },
      {
        Color: "Blue",
        Storage: "512 GB",
        Model: ["MLQG3", "MLN83", "MLEC3"],
      },
      {
        Color: "Pink",
        Storage: "128 GB",
        Model: ["MLPH3", "MLMN3", "MLDW3"],
      },
      {
        Color: "Pink",
        Storage: "256 GB",
        Model: ["MLQ83", "MLMY3", "MLE23"],
      },
      {
        Color: "Pink",
        Storage: "512 GB",
        Model: ["MLQE3", "MLN43", "MLE93"],
      },
      {
        Color: "Green",
        Storage: "128 GB",
        Model: ["MNGD3", "MNG93", "MNGK3"],
      },
      {
        Color: "Green",
        Storage: "256 GB",
        Model: ["MNGE3", "MNGA3", "MNGL3"],
      },
      {
        Color: "Green",
        Storage: "512 GB",
        Model: ["MNGF3", "MNGC3", "MNGM3"],
      },
    ],
  },
  {
    productId: "iPhone14-Plus-2024-Blue",
    brand: "Apple",
    Generation: "iPhone 14 Plus",
    title: "Apple iPhone 14 Plus (Blue, 128 GB)",
    imageURLLarge: "https://rb.gy/co3izh",
    deliveryCost: "Free",
    spec: [
      "128 GB ROM",
      "17.02 cm (6.7 inch) Super Retina XDR Display",
      "12MP + 12MP | 12MP Front Camera",
      "A15 Bionic Chip, 6 Core Processor Processor",
      " 1 Year Manufacturer Warranty For Device And 6 Months Manufacturer Warranty For In-Box Accessories",
    ],
    price: "68,900",
    colors: ["Blue", "Silver", "Gold", "Deep Purple"],
    ANumber: [],
    Bootrom: "",
    FCCID: [],
    InternalName: "D28AP",
    Identifier: "iPhone14,8",
    Models: [
      {
        Color: "Blue",
        Storage: "128 GB",
        Model: ["MQ523", "MQ3W3", "MQ3A3"],
      },
      {
        Color: "Blue",
        Storage: "256 GB",
        Model: ["MQ583", "MQ423", "MQ3G3"],
      },
      {
        Color: "Blue",
        Storage: "512 GB",
        Model: ["MQ5G3", "MQ493", "MQ3Q3"],
      },
      {
        Color: "Midnight",
        Storage: "128 GB",
        Model: ["MQ4X3", "MQ3R3", "MQ353"],
      },
      {
        Color: "Midnight",
        Storage: "256 GB",
        Model: ["MQ533", "MQ3X3", "MQ3C3"],
      },
      {
        Color: "Midnight",
        Storage: "512 GB",
        Model: ["MQ593", "MQ433", "MQ3H3"],
      },
      {
        Color: "Starlight",
        Storage: "128 GB",
        Model: ["MQ4Y3", "MQ3T3", "MQ363"],
      },
      {
        Color: "Starlight",
        Storage: "256 GB",
        Model: ["MQ553", "MQ3Y3", "MQ3D3"],
      },
      {
        Color: "Starlight",
        Storage: "512 GB",
        Model: ["MQ5D3", "MQ443", "MQ3J3"],
      },
      {
        Color: "Red",
        Storage: "128 GB",
        Model: ["MQ513", "MQ3V3", "MQ393"],
      },
      {
        Color: "Red",
        Storage: "256 GB",
        Model: ["MQ573", "MQ413", "MQ3F3"],
      },
      {
        Color: "Red",
        Storage: "512 GB",
        Model: ["MQ5F3", "MQ473", "MQ3P3"],
      },
      {
        Color: "Purple",
        Storage: "128 GB",
        Model: ["MQ503", "MQ3U3", "MQ373"],
      },
      {
        Color: "Purple",
        Storage: "256 GB",
        Model: ["MQ563", "MQ403", "MQ3E3"],
      },
      {
        Color: "Purple",
        Storage: "512 GB",
        Model: ["MQ5E3", "MQ463", "MQ3K3"],
      },
    ],
  },
  {
    productId: "iPhone14-Pro-2024-Space_Black",
    brand: "Apple",
    Generation: "iPhone 14 Pro",
    title: "Apple iPhone 14 Pro (Space Black, 128 GB)",
    imageURLLarge: "https://rb.gy/80ikn7",
    deliveryCost: "Free",
    spec: [
      "256 GB ROM",
      "15.49 cm (6.1 inch) Super Retina XDR Display",
      "48MP + 12MP + 12MP | 12MP Front Camera",
      "A16 Bionic Chip, 6 Core Processor Processor",
      " 1 Year Manufacturer Warranty For Device And 6 Months Manufacturer Warranty For In-Box Accessories",
    ],
    price: "1,29,900",
    colors: ["Space Black", "Silver", "Gold", "Deep Purple"],

    InternalName: "D73AP",
    Identifier: "iPhone15,2",
    Models: [
      {
        Color: "Deep Purple",
        Storage: "128 GB",
        Model: ["MQ0E3", "MQ0G3", "MQ0D3"],
      },
      {
        Color: "Deep Purple",
        Storage: "256 GB",
        Model: ["MQ1D3", "MQ1F3", "MQ1C3"],
      },
      {
        Color: "Deep Purple",
        Storage: "512 GB",
        Model: ["MQ273", "MQ293", "MQ263"],
      },
      {
        Color: "Deep Purple",
        Storage: "1 TB",
        Model: ["MQ303", "MQ323", "MQ2Y3"],
      },
      {
        Color: "Gold",
        Storage: "128 GB",
        Model: ["MQ063", "MQ083", "MQ053"],
      },
      {
        Color: "Gold",
        Storage: "256 GB",
        Model: ["MQ163", "MQ183", "MQ143"],
      },
      {
        Color: "Gold",
        Storage: "512 GB",
        Model: ["MQ213", "MQ233", "MQ203"],
      },
      {
        Color: "Gold",
        Storage: "1 TB",
        Model: ["MQ2T3", "MQ2V3", "MQ2R3"],
      },
      {
        Color: "Silver",
        Storage: "128 GB",
        Model: ["MQ003", "MQ023", "MPXY3"],
      },
      {
        Color: "Silver",
        Storage: "256 GB",
        Model: ["MQ0X3", "MQ103", "MQ0W3"],
      },
      {
        Color: "Silver",
        Storage: "512 GB",
        Model: ["MQ1U3", "MQ1W3", "MQ1R3"],
      },
      {
        Color: "Silver",
        Storage: "1 TB",
        Model: ["MQ2L3", "MQ2N3", "MQ2K3"],
      },
      {
        Color: "Space Black",
        Storage: "128 GB",
        Model: ["MPXT3", "MPXV3", "MPXR3"],
      },
      {
        Color: "Space Black",
        Storage: "256 GB",
        Model: ["MQ0N3", "MQ0T3", "MQ0M3"],
      },
      {
        Color: "Space Black",
        Storage: "512 GB",
        Model: ["MQ1K3", "MQ1M3", "MQ1J3"],
      },
      {
        Color: "Space Black",
        Storage: "1 TB",
        Model: ["MQ2E3", "MQ2G3", "MQ2D3"],
      },
    ],
  },
  {
    productId: "iPhone14-Pro-Max-2024-Space_Black",
    brand: "Apple",
    Generation: "iPhone 14 Pro Max",
    title: "Apple iPhone 14 Pro (Space Black, 128 GB)",
    imageURLLarge: "https://rb.gy/7ersrs",
    deliveryCost: "Free",
    spec: [
      "1 TB ROM",
      "17.02 cm (6.7 inch) Super Retina XDR Display",
      "48MP + 12MP + 12MP | 12MP Front Camera",
      "A16 Bionic Chip, 6 Core Processor Processor",
      " 1 Year Manufacturer Warranty For Device And 6 Months Manufacturer Warranty For In-Box Accessories",
    ],
    colors: ["Space Black", "Silver", "Gold", "Deep Purple"],
    price: "1,37,999",
    InternalName: "D74AP",
    Identifier: "iPhone15,3",
    Models: [
      {
        Color: "Deep Purple",
        Storage: "128 GB",
        Model: ["MQ9T3", "MQ8R3", "MQ863"],
      },
      {
        Color: "Deep Purple",
        Storage: "256 GB",
        Model: ["MQ9X3", "MQ8W3", "MQ8A3"],
      },
      {
        Color: "Deep Purple",
        Storage: "512 GB",
        Model: ["MQAM3", "MQ913", "MQ8G3"],
      },
      {
        Color: "Deep Purple",
        Storage: "1 TB",
        Model: ["MQC53", "MQ953", "MQ8M3"],
      },
      {
        Color: "Gold",
        Storage: "128 GB",
        Model: ["MQ9R3", "MQ8Q3", "MQ853"],
      },
      {
        Color: "Gold",
        Storage: "256 GB",
        Model: ["MQ9W3", "MQ8V3", "MQ893"],
      },
      {
        Color: "Gold",
        Storage: "512 GB",
        Model: ["MQAJ3", "MQ903", "MQ8F3"],
      },
      {
        Color: "Gold",
        Storage: "1 TB",
        Model: ["MQC43", "MQ943", "MQ8L3"],
      },
      {
        Color: "Silver",
        Storage: "128 GB",
        Model: ["MQ9Q3", "MQ8P3", "MQ843"],
      },
      {
        Color: "Silver",
        Storage: "256 GB",
        Model: ["MQ9V3", "MQ8U3", "MQ883"],
      },
      {
        Color: "Silver",
        Storage: "512 GB",
        Model: ["MQAH3", "MQ8Y3", "MQ8E3"],
      },
      {
        Color: "Silver",
        Storage: "1 TB",
        Model: ["MQC33", "MQ933", "MQ8J3"],
      },
      {
        Color: "Space Black",
        Storage: "128 GB",
        Model: ["MQ9P3", "MQ8N3", "MQ833"],
      },
      {
        Color: "Space Black",
        Storage: "256 GB",
        Model: ["MQ9U3", "MQ8T3", "MQ873"],
      },
      {
        Color: "Space Black",
        Storage: "512 GB",
        Model: ["MQAF3", "MQ8X3", "MQ8D3"],
      },
      {
        Color: "Space Black",
        Storage: "1 TB",
        Model: ["MQC23", "MQ923", "MQ8H3"],
      },
    ],
  },
  {
    productId: "iPhone14-2024-Yellow",
    brand: "Apple",
    Generation: "iPhone 14",
    title: "Apple iPhone 14 (Yellow, 128 GB)",
    imageURLLarge: "https://rb.gy/2i87vv",
    deliveryCost: "Free",
    spec: [
      "256 GB ROM",
      "17.02 cm (6.7 inch) Super Retina XDR Display",
      "12MP + 12MP | 12MP Front Camera",
      "A15 Bionic Chip, 6 Core Processor Processor",
      " 1 Year Manufacturer Warranty For Device And 6 Months Manufacturer Warranty For In-Box Accessories",
    ],
    price: "63,900",
    colors: ["Yellow", "Space Black", "Silver", "Deep Purple"],
    ANumber: [],
    Bootrom: "",
    FCCID: [],
    InternalName: "D27AP",
    Identifier: "iPhone14,7",
    Models: [
      {
        Color: "Blue",
        Storage: "128 GB",
        Model: ["MPVN3", "MPVH3", "MPVG3"],
      },
      {
        Color: "Blue",
        Storage: "256 GB",
        Model: ["MPWP3", "MPWM3", "MPWL3"],
      },
      {
        Color: "Blue",
        Storage: "512 GB",
        Model: ["MPXN3", "MPXL3", "MPXK3"],
      },
      {
        Color: "Midnight",
        Storage: "128 GB",
        Model: ["MPUF3", "MPUA3", "MPU93"],
      },
      {
        Color: "Midnight",
        Storage: "256 GB",
        Model: ["MPVX3", "MPVV3", "MPVU3"],
      },
      {
        Color: "Midnight",
        Storage: "512 GB",
        Model: ["MPWW3", "MPWU3", "MPWT3"],
      },
      {
        Color: "Starlight",
        Storage: "128 GB",
        Model: ["MPUR3", "MPUN3", "MPUJ3"],
      },
      {
        Color: "Starlight",
        Storage: "256 GB",
        Model: ["MPW43", "MPW23", "MPW13"],
      },
      {
        Color: "Starlight",
        Storage: "512 GB",
        Model: ["MPX33", "MPX13", "MPX03"],
      },
      {
        Color: "Red",
        Storage: "128 GB",
        Model: ["MPVA3", "MPV73", "MPV63"],
      },
      {
        Color: "Red",
        Storage: "256 GB",
        Model: ["MPWH3", "MPWF3", "MPWE3"],
      },
      {
        Color: "Red",
        Storage: "512 GB",
        Model: ["MPXG3", "MPXE3", "MPXD3"],
      },
      {
        Color: "Purple",
        Storage: "128 GB",
        Model: ["MPV03", "MPUX3", "MPUW3"],
      },
      {
        Color: "Purple",
        Storage: "256 GB",
        Model: ["MPWA3", "MPW83", "MPW73"],
      },
      {
        Color: "Purple",
        Storage: "512 GB",
        Model: ["MPX93", "MPX73", "MPX63"],
      },
    ],
  },
];

const allBrandData = [iphone];
